### ISSUE TITLE
Create a Platformnomics page based on existing Ubernomics

### ISSUE THREAD

**Issue by rufuspollock** [open-revolution/openrevolution.net#15]
Have existing quite detailed essay at https://rufuspollock.com/ubernomics/

To start with can just migrate this over. Later (separate issue) can enhance and extend this.

## Acceptance

* [x] https://rufuspollock.com/ubernomics/ is migrated to e.g. /platformnomics/
* [x] Link from navbar or similar

## Tasks

* [x] Copy over
* [x] Tidy up e.g. fix style instructions
* [x] Add to navbar

**Comment by rufuspollock** [comment]
FIXED. All done (added link to navbar recently in https://github.com/open-revolution/openrevolution.net/commit/82ba7987ade53179d6c5cae063d1132556e3f3b7)
