### ISSUE TITLE
[epic] How to fund Open [Source] Software

### ISSUE THREAD

**Issue by rufuspollock** [open-revolution/openrevolution.net#16]
This is an areas with a big demand in that people keep asking about it [1] including with an EU funded research project ~ a year ago. I've also talked this through a few times and its discussed in the book and its one of the bigger (and more complex) application of the remuneration rights model (given complexity of assessing "value" for the fund allocation).

[1] examples being e.g.

* Roads and bridges for Ford Foundation (i gave detailed input)
* Numerous visible examples of critical free/open source not being funded e.g. heartbleed bug, log4j bug (dec 2021)
* Open Source has a Funding Problem (StackOverflow blog) https://stackoverflow.blog/2021/01/07/open-source-has-a-funding-problem/
  
  <img height="150" src="https://user-images.githubusercontent.com/180658/150679495-15cf21e1-3728-446c-90bf-9aab65df913b.png" />

Existing materials

* [ ] https://rufuspollock.com/open-source-software-and-government/ cf
* [ ] Call with the EU research project (feb 25 2021)
	* [ ] Includes ["Value Capture Challenge for Open Source including decision tree showing outcomes & social value for proprietary and open production"](https://docs.google.com/drawings/d/1RSOuoOPjkE6XeujYNUFzCWMICkXOw6WbRI2DdpeFLvU/edit) diagram showing outcome tree explaining issue in funding public goods
* [ ] Book itself
* [ ] Various (maybe recorded discussions) about value allocation mechanism for software
